const SETTIGNS = {
    DURATION_OF_ENEMY_COMES: 9,
    DURATION_OF_HREALTH_COMES: 9,
    DURATION_OF_BOOSTER_COMES: 9,
    DURATION_OF_SHIELD_COMES: 9,
    PLAYER_BULLETS_DENSITY: 9,
    ENEMY_BULLETS_DENSITY: 9,
    ENEMY_FALLING_SPEED: 2,
};

export default SETTIGNS;
